export const languages = {
    vi: {
      haveAcc: 'Đã có tài khoản',
      login: 'Đăng nhập',
      register: 'Đăng ký',
      forgotPassword: 'Quên mật khẩu',
      changePassword: 'Đổi mật khẩu',
      home: 'Trang chủ',
      favorite: 'Yêu thích',
      favorited: 'Đã yêu thích',
      search: 'Tìm kiếm',
      searchInput: 'Từ khóa tìm kiếm',
      cat: 'Danh mục',
      google: 'Đăng nhập với Google',
      buy: 'Mua ngay',
      more: 'Xem thêm',
      course: 'Khóa học',
      instructor: 'Giảng viên',
      newRelease: 'Mới cập nhật',
      recommend: 'Gợi ý cho bạn',
      topRate: 'Khóa học nổi bật',
      topSell: 'Bán chạy nhất',
      free: 'Miễn phí',
      click: 'Nhấn vào bài học để xem video',
      share: 'Chia sẻ',
      lesson: 'Bài học',
      exercise: 'Bài tập',
      desc: 'Mô tả',
      rating: 'Đánh giá',
      subject: 'Chủ đề',
      hour: 'Giờ',
      backCourse: 'Quay lại khóa học',
      historySearch: 'Lịch sử tìm kiếm',
      emptySearch: 'Không có kết quả tìm kiếm',
      name: 'Tên',
      phone: 'Số điện thoại',
      skill: 'Kỹ năng',
      field: 'Lĩnh vực',
      yourCourse: 'Khóa học của bạn',
      pleaseName: 'Vui lòng nhập tên',
      pleasePhone: 'Vui lòng nhập số điện thoại',
      pleasePass: 'Vui lòng nhập mật khẩu',
      pleaseCPass: 'Vui lòng xác nhận mật khẩu',
      notMatched: 'Mật khẩu không trùng khớp',
      loginErr: 'Email hoặc mật khẩu không đúng',
      checkEmail: 'Vui lòng kiểm tra hộp thư email',
      success: 'Thành công',
      pleaseEmail: 'Vui lòng nhập email',
      password: 'Mật khẩu',
      serverError: 'Hệ thống bị lỗi, thử lại',
      buyCofirm: 'Bạn muốn tham gia khóa học?',
      cancel: 'Hủy',
      ok: 'Chập nhận',
      profile: 'Quản lý tài khoản',
      setting: 'Cấu hình ứng dụng',
      logOut: 'Đăng xuất',
      cpassword: 'Nhập lại mật khẩu',
      opassword: 'Mật khẩu cũ',
      npassword: 'Mật khẩu mới',
      upload: 'Tải lên',
      type: 'Loại tài khoản',
      update: 'Cập nhật',
      pleaseOPass: 'Vui lòng nhập mật khẩu cũ',
      pleaseNPass: 'Vui lòng nhập mật khẩu mới',
      errorChangePass: 'Mật khẩu cũ không đúng hoặc không giống mật khẩu mới',
      emailNoRegister: 'Email chưa được đăng ký',
      sendEmail: 'Gửi email',
      or: 'Hoặc',
      emailExisted: 'Email hoặc số điện thoại đã tồn tại',
      learn: 'Các bạn sẽ được học',
      requirment: 'Yêu cầu',
      moreInfo: 'Thông tin thêm',
      requestBuy: 'Bạn phải mua khóa học mới có thể xem được bài học.',
      empty: 'Không có khóa học nào',
      student: 'Học viên',
      delete: 'Xóa',
      time: 'Thời lượng',
      emptyLesson: 'Không có bài tập',
      listLesson: 'Danh sách bài tập',
      courseInstructor: 'Khóa học',
    },
    en: {
      haveAcc: 'Already have account',
        login: 'Login',
        register: 'Register',
        forgotPassword: 'Forgot password',
        changePassword: 'Change password',
        home: 'Home',
        favorite: 'Favorite',
        favorited: 'Favorited',
        search: 'Search',
        cat: 'Categories',
        google: 'Login with Google',
        buy: 'Buy now',
        more: 'More',
        course: 'Courses',
        instructor: 'Instructors',
        newRelease: 'New release',
        recommend: 'Recommend for you',
        topRate: 'Top rating',
        topSell: 'Top selling',
        free: 'Free',
        click: 'Click lesson to watch video',
        share: 'Share',
        lesson: 'Lessons',
        exercise: 'Exercises',
        desc: 'Desc',
        rating: 'Rating',
        subject: 'Subject',
        hour: 'Hours',
        backCourse: 'Back to course',
        historySearch: 'History search',
        emptySearch: 'No search result',
        name: 'Name',
        phone: 'Phone',
        skill: 'Skills',
        field: 'Fields',
        yourCourse: 'Your courses',
        pleaseName: 'Please input name',
        pleasePhone: 'Please input phone number',
        pleasePass: 'Please input password',
        pleaseCPass: 'Please input confirm password',
        notMatched: 'Password not matched',
        loginErr: 'Email or Password is invalid',
        checkEmail: 'Please check your email to complete',
        success: 'Success',
        pleaseEmail: 'Please input email',
        password: 'Password',
        serverError: 'Sever error',
        buyCofirm: 'Are you join this course',
        cancel: 'Cancel',
        ok: 'Confirm',
        profile: 'Profile',
        setting: 'Setting',
        logOut: 'Log out',
        cpassword: 'Cofirm password',
        opassword: 'Old password',
        npassword: 'New password',
        upload: 'Upload',
        type: 'Account type',
        update: 'Update',
        pleaseOPass: 'Please input old password',
        pleaseNPass: 'Please input new password',
        errorChangePass: 'Old password is not correct',
        emailNoRegister: 'Email is not registered',
        sendEmail: 'Send email',
        or: 'OR',
        emailExisted: 'Email or phone number is existed',
        learn: 'You will be learn',
        requirment: 'Requirments',
        moreInfo: 'More infomation',
        requestBuy: 'You must be buy course to watch video.',
        empty: 'There is no course',
        student: 'Students',
        delete: 'Delete',
        searchInput: 'Text input',
        time: 'Time',
        emptyLesson: 'No lesson',
        listLesson: 'List lessons',
        courseInstructor: 'Courses',

    },
  };
  